# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='owner',
            field=models.CharField(default=2, max_length=16),
            preserve_default=False,
        ),
    ]
